[package]

name = "logger"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>", "Michael Reinhard <mcreinhard@gmail.com>"]
version = "0.1.0"

[lib]

name = "logger"
path = "src/lib.rs"

[dependencies.iron]

git = "https://github.com/iron/iron.git"

