[package]

name = "logger"
authors = ["Michael Reinhard <mcreinhard@gmail.com>"]
version = "0.1.0"
readme = "README.md"
tags = ["web", "server", "middleware", "iron", "core", "logger"]

[[lib]]

name = "logger"
path = "src/lib.rs"

[dependencies.iron]

git = "https://github.com/iron/iron.git"

